/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef _Included_com_jqk_first_FFmpegHelloWorld
#define _Included_com_jqk_first_FFmpegHelloWorld
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_jqk_first_FFmpegHelloWorld_urlprotocolinfo(JNIEnv *env, jobject obj);

JNIEXPORT jstring JNICALL Java_com_jqk_first_FFmpegHelloWorld_avformatinfo(JNIEnv *env, jobject obj);

JNIEXPORT jstring JNICALL Java_com_jqk_first_FFmpegHelloWorld_avcodecinfo(JNIEnv *env, jobject obj);

JNIEXPORT jstring JNICALL Java_com_jqk_first_FFmpegHelloWorld_avfilterinfo(JNIEnv *env, jobject obj);

JNIEXPORT jstring JNICALL Java_com_jqk_first_FFmpegHelloWorld_configurationinfo(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif